/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PromocoesRouteImport } from './routes/promocoes'
import { Route as PlanosRouteImport } from './routes/planos'
import { Route as LoginRouteImport } from './routes/login'
import { Route as FavoritosRouteImport } from './routes/favoritos'
import { Route as DivulgarRouteImport } from './routes/divulgar'
import { Route as CategoriasRouteImport } from './routes/categorias'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EmpresaSlugRouteImport } from './routes/empresa.$slug'
import { Route as CategoriasSlugRouteImport } from './routes/categorias.$slug'

const PromocoesRoute = PromocoesRouteImport.update({
  id: '/promocoes',
  path: '/promocoes',
  getParentRoute: () => rootRouteImport,
} as any)
const PlanosRoute = PlanosRouteImport.update({
  id: '/planos',
  path: '/planos',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const FavoritosRoute = FavoritosRouteImport.update({
  id: '/favoritos',
  path: '/favoritos',
  getParentRoute: () => rootRouteImport,
} as any)
const DivulgarRoute = DivulgarRouteImport.update({
  id: '/divulgar',
  path: '/divulgar',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriasRoute = CategoriasRouteImport.update({
  id: '/categorias',
  path: '/categorias',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EmpresaSlugRoute = EmpresaSlugRouteImport.update({
  id: '/empresa/$slug',
  path: '/empresa/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriasSlugRoute = CategoriasSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => CategoriasRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/categorias': typeof CategoriasRouteWithChildren
  '/divulgar': typeof DivulgarRoute
  '/favoritos': typeof FavoritosRoute
  '/login': typeof LoginRoute
  '/planos': typeof PlanosRoute
  '/promocoes': typeof PromocoesRoute
  '/categorias/$slug': typeof CategoriasSlugRoute
  '/empresa/$slug': typeof EmpresaSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/categorias': typeof CategoriasRouteWithChildren
  '/divulgar': typeof DivulgarRoute
  '/favoritos': typeof FavoritosRoute
  '/login': typeof LoginRoute
  '/planos': typeof PlanosRoute
  '/promocoes': typeof PromocoesRoute
  '/categorias/$slug': typeof CategoriasSlugRoute
  '/empresa/$slug': typeof EmpresaSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/categorias': typeof CategoriasRouteWithChildren
  '/divulgar': typeof DivulgarRoute
  '/favoritos': typeof FavoritosRoute
  '/login': typeof LoginRoute
  '/planos': typeof PlanosRoute
  '/promocoes': typeof PromocoesRoute
  '/categorias/$slug': typeof CategoriasSlugRoute
  '/empresa/$slug': typeof EmpresaSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/categorias'
    | '/divulgar'
    | '/favoritos'
    | '/login'
    | '/planos'
    | '/promocoes'
    | '/categorias/$slug'
    | '/empresa/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/categorias'
    | '/divulgar'
    | '/favoritos'
    | '/login'
    | '/planos'
    | '/promocoes'
    | '/categorias/$slug'
    | '/empresa/$slug'
  id:
    | '__root__'
    | '/'
    | '/categorias'
    | '/divulgar'
    | '/favoritos'
    | '/login'
    | '/planos'
    | '/promocoes'
    | '/categorias/$slug'
    | '/empresa/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CategoriasRoute: typeof CategoriasRouteWithChildren
  DivulgarRoute: typeof DivulgarRoute
  FavoritosRoute: typeof FavoritosRoute
  LoginRoute: typeof LoginRoute
  PlanosRoute: typeof PlanosRoute
  PromocoesRoute: typeof PromocoesRoute
  EmpresaSlugRoute: typeof EmpresaSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/promocoes': {
      id: '/promocoes'
      path: '/promocoes'
      fullPath: '/promocoes'
      preLoaderRoute: typeof PromocoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/planos': {
      id: '/planos'
      path: '/planos'
      fullPath: '/planos'
      preLoaderRoute: typeof PlanosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/favoritos': {
      id: '/favoritos'
      path: '/favoritos'
      fullPath: '/favoritos'
      preLoaderRoute: typeof FavoritosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/divulgar': {
      id: '/divulgar'
      path: '/divulgar'
      fullPath: '/divulgar'
      preLoaderRoute: typeof DivulgarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categorias': {
      id: '/categorias'
      path: '/categorias'
      fullPath: '/categorias'
      preLoaderRoute: typeof CategoriasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/empresa/$slug': {
      id: '/empresa/$slug'
      path: '/empresa/$slug'
      fullPath: '/empresa/$slug'
      preLoaderRoute: typeof EmpresaSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categorias/$slug': {
      id: '/categorias/$slug'
      path: '/$slug'
      fullPath: '/categorias/$slug'
      preLoaderRoute: typeof CategoriasSlugRouteImport
      parentRoute: typeof CategoriasRoute
    }
  }
}

interface CategoriasRouteChildren {
  CategoriasSlugRoute: typeof CategoriasSlugRoute
}

const CategoriasRouteChildren: CategoriasRouteChildren = {
  CategoriasSlugRoute: CategoriasSlugRoute,
}

const CategoriasRouteWithChildren = CategoriasRoute._addFileChildren(
  CategoriasRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CategoriasRoute: CategoriasRouteWithChildren,
  DivulgarRoute: DivulgarRoute,
  FavoritosRoute: FavoritosRoute,
  LoginRoute: LoginRoute,
  PlanosRoute: PlanosRoute,
  PromocoesRoute: PromocoesRoute,
  EmpresaSlugRoute: EmpresaSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
