/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as PromocoesRouteImport } from './routes/promocoes'
import { Route as PlanosRouteImport } from './routes/planos'
import { Route as LoginRouteImport } from './routes/login'
import { Route as FavoritosRouteImport } from './routes/favoritos'
import { Route as EmpresasRouteImport } from './routes/empresas'
import { Route as DivulgarRouteImport } from './routes/divulgar'
import { Route as BuscarRouteImport } from './routes/buscar'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PoliticasIndexRouteImport } from './routes/politicas.index'
import { Route as CategoriasIndexRouteImport } from './routes/categorias.index'
import { Route as PoliticasSlugRouteImport } from './routes/politicas.$slug'
import { Route as EmpresaSlugRouteImport } from './routes/empresa.$slug'
import { Route as CheckoutRetornoRouteImport } from './routes/checkout.retorno'
import { Route as CategoriasSlugRouteImport } from './routes/categorias.$slug'
import { Route as AuthenticatedReivindicarRouteImport } from './routes/_authenticated.reivindicar'
import { Route as AuthenticatedMinhaEmpresaRouteImport } from './routes/_authenticated.minha-empresa'
import { Route as AuthenticatedContaRouteImport } from './routes/_authenticated.conta'
import { Route as AuthenticatedCompletarCadastroRouteImport } from './routes/_authenticated.completar-cadastro'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated.admin'
import { Route as AuthenticatedAdminUsuariosRouteImport } from './routes/_authenticated.admin.usuarios'
import { Route as AuthenticatedAdminReivindicacoesRouteImport } from './routes/_authenticated.admin.reivindicacoes'
import { Route as AuthenticatedAdminPromocoesRouteImport } from './routes/_authenticated.admin.promocoes'
import { Route as AuthenticatedAdminPoliticasRouteImport } from './routes/_authenticated.admin.politicas'
import { Route as AuthenticatedAdminPlanosRouteImport } from './routes/_authenticated.admin.planos'
import { Route as AuthenticatedAdminMigracoesRouteImport } from './routes/_authenticated.admin.migracoes'
import { Route as AuthenticatedAdminInstituicoesRouteImport } from './routes/_authenticated.admin.instituicoes'
import { Route as AuthenticatedAdminEmpresasRouteImport } from './routes/_authenticated.admin.empresas'
import { Route as AuthenticatedAdminCategoriasRouteImport } from './routes/_authenticated.admin.categorias'
import { Route as AuthenticatedAdminBannersRouteImport } from './routes/_authenticated.admin.banners'
import { Route as ApiPublicPaymentsWebhookRouteImport } from './routes/api/public/payments/webhook'
import { Route as AuthenticatedEmpresaIdPromocoesRouteImport } from './routes/_authenticated.empresa.$id.promocoes'
import { Route as AuthenticatedEmpresaIdPostsRouteImport } from './routes/_authenticated.empresa.$id.posts'
import { Route as AuthenticatedEmpresaIdEditarRouteImport } from './routes/_authenticated.empresa.$id.editar'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const PromocoesRoute = PromocoesRouteImport.update({
  id: '/promocoes',
  path: '/promocoes',
  getParentRoute: () => rootRouteImport,
} as any)
const PlanosRoute = PlanosRouteImport.update({
  id: '/planos',
  path: '/planos',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const FavoritosRoute = FavoritosRouteImport.update({
  id: '/favoritos',
  path: '/favoritos',
  getParentRoute: () => rootRouteImport,
} as any)
const EmpresasRoute = EmpresasRouteImport.update({
  id: '/empresas',
  path: '/empresas',
  getParentRoute: () => rootRouteImport,
} as any)
const DivulgarRoute = DivulgarRouteImport.update({
  id: '/divulgar',
  path: '/divulgar',
  getParentRoute: () => rootRouteImport,
} as any)
const BuscarRoute = BuscarRouteImport.update({
  id: '/buscar',
  path: '/buscar',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PoliticasIndexRoute = PoliticasIndexRouteImport.update({
  id: '/politicas/',
  path: '/politicas/',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriasIndexRoute = CategoriasIndexRouteImport.update({
  id: '/categorias/',
  path: '/categorias/',
  getParentRoute: () => rootRouteImport,
} as any)
const PoliticasSlugRoute = PoliticasSlugRouteImport.update({
  id: '/politicas/$slug',
  path: '/politicas/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const EmpresaSlugRoute = EmpresaSlugRouteImport.update({
  id: '/empresa/$slug',
  path: '/empresa/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRetornoRoute = CheckoutRetornoRouteImport.update({
  id: '/checkout/retorno',
  path: '/checkout/retorno',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriasSlugRoute = CategoriasSlugRouteImport.update({
  id: '/categorias/$slug',
  path: '/categorias/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedReivindicarRoute =
  AuthenticatedReivindicarRouteImport.update({
    id: '/reivindicar',
    path: '/reivindicar',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedMinhaEmpresaRoute =
  AuthenticatedMinhaEmpresaRouteImport.update({
    id: '/minha-empresa',
    path: '/minha-empresa',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedContaRoute = AuthenticatedContaRouteImport.update({
  id: '/conta',
  path: '/conta',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedCompletarCadastroRoute =
  AuthenticatedCompletarCadastroRouteImport.update({
    id: '/completar-cadastro',
    path: '/completar-cadastro',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminUsuariosRoute =
  AuthenticatedAdminUsuariosRouteImport.update({
    id: '/usuarios',
    path: '/usuarios',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminReivindicacoesRoute =
  AuthenticatedAdminReivindicacoesRouteImport.update({
    id: '/reivindicacoes',
    path: '/reivindicacoes',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminPromocoesRoute =
  AuthenticatedAdminPromocoesRouteImport.update({
    id: '/promocoes',
    path: '/promocoes',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminPoliticasRoute =
  AuthenticatedAdminPoliticasRouteImport.update({
    id: '/politicas',
    path: '/politicas',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminPlanosRoute =
  AuthenticatedAdminPlanosRouteImport.update({
    id: '/planos',
    path: '/planos',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminMigracoesRoute =
  AuthenticatedAdminMigracoesRouteImport.update({
    id: '/migracoes',
    path: '/migracoes',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminInstituicoesRoute =
  AuthenticatedAdminInstituicoesRouteImport.update({
    id: '/instituicoes',
    path: '/instituicoes',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminEmpresasRoute =
  AuthenticatedAdminEmpresasRouteImport.update({
    id: '/empresas',
    path: '/empresas',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminCategoriasRoute =
  AuthenticatedAdminCategoriasRouteImport.update({
    id: '/categorias',
    path: '/categorias',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminBannersRoute =
  AuthenticatedAdminBannersRouteImport.update({
    id: '/banners',
    path: '/banners',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const ApiPublicPaymentsWebhookRoute =
  ApiPublicPaymentsWebhookRouteImport.update({
    id: '/api/public/payments/webhook',
    path: '/api/public/payments/webhook',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedEmpresaIdPromocoesRoute =
  AuthenticatedEmpresaIdPromocoesRouteImport.update({
    id: '/empresa/$id/promocoes',
    path: '/empresa/$id/promocoes',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedEmpresaIdPostsRoute =
  AuthenticatedEmpresaIdPostsRouteImport.update({
    id: '/empresa/$id/posts',
    path: '/empresa/$id/posts',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedEmpresaIdEditarRoute =
  AuthenticatedEmpresaIdEditarRouteImport.update({
    id: '/empresa/$id/editar',
    path: '/empresa/$id/editar',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/buscar': typeof BuscarRoute
  '/divulgar': typeof DivulgarRoute
  '/empresas': typeof EmpresasRoute
  '/favoritos': typeof FavoritosRoute
  '/login': typeof LoginRoute
  '/planos': typeof PlanosRoute
  '/promocoes': typeof PromocoesRoute
  '/reset-password': typeof ResetPasswordRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/completar-cadastro': typeof AuthenticatedCompletarCadastroRoute
  '/conta': typeof AuthenticatedContaRoute
  '/minha-empresa': typeof AuthenticatedMinhaEmpresaRoute
  '/reivindicar': typeof AuthenticatedReivindicarRoute
  '/categorias/$slug': typeof CategoriasSlugRoute
  '/checkout/retorno': typeof CheckoutRetornoRoute
  '/empresa/$slug': typeof EmpresaSlugRoute
  '/politicas/$slug': typeof PoliticasSlugRoute
  '/categorias/': typeof CategoriasIndexRoute
  '/politicas/': typeof PoliticasIndexRoute
  '/admin/banners': typeof AuthenticatedAdminBannersRoute
  '/admin/categorias': typeof AuthenticatedAdminCategoriasRoute
  '/admin/empresas': typeof AuthenticatedAdminEmpresasRoute
  '/admin/instituicoes': typeof AuthenticatedAdminInstituicoesRoute
  '/admin/migracoes': typeof AuthenticatedAdminMigracoesRoute
  '/admin/planos': typeof AuthenticatedAdminPlanosRoute
  '/admin/politicas': typeof AuthenticatedAdminPoliticasRoute
  '/admin/promocoes': typeof AuthenticatedAdminPromocoesRoute
  '/admin/reivindicacoes': typeof AuthenticatedAdminReivindicacoesRoute
  '/admin/usuarios': typeof AuthenticatedAdminUsuariosRoute
  '/empresa/$id/editar': typeof AuthenticatedEmpresaIdEditarRoute
  '/empresa/$id/posts': typeof AuthenticatedEmpresaIdPostsRoute
  '/empresa/$id/promocoes': typeof AuthenticatedEmpresaIdPromocoesRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/buscar': typeof BuscarRoute
  '/divulgar': typeof DivulgarRoute
  '/empresas': typeof EmpresasRoute
  '/favoritos': typeof FavoritosRoute
  '/login': typeof LoginRoute
  '/planos': typeof PlanosRoute
  '/promocoes': typeof PromocoesRoute
  '/reset-password': typeof ResetPasswordRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/completar-cadastro': typeof AuthenticatedCompletarCadastroRoute
  '/conta': typeof AuthenticatedContaRoute
  '/minha-empresa': typeof AuthenticatedMinhaEmpresaRoute
  '/reivindicar': typeof AuthenticatedReivindicarRoute
  '/categorias/$slug': typeof CategoriasSlugRoute
  '/checkout/retorno': typeof CheckoutRetornoRoute
  '/empresa/$slug': typeof EmpresaSlugRoute
  '/politicas/$slug': typeof PoliticasSlugRoute
  '/categorias': typeof CategoriasIndexRoute
  '/politicas': typeof PoliticasIndexRoute
  '/admin/banners': typeof AuthenticatedAdminBannersRoute
  '/admin/categorias': typeof AuthenticatedAdminCategoriasRoute
  '/admin/empresas': typeof AuthenticatedAdminEmpresasRoute
  '/admin/instituicoes': typeof AuthenticatedAdminInstituicoesRoute
  '/admin/migracoes': typeof AuthenticatedAdminMigracoesRoute
  '/admin/planos': typeof AuthenticatedAdminPlanosRoute
  '/admin/politicas': typeof AuthenticatedAdminPoliticasRoute
  '/admin/promocoes': typeof AuthenticatedAdminPromocoesRoute
  '/admin/reivindicacoes': typeof AuthenticatedAdminReivindicacoesRoute
  '/admin/usuarios': typeof AuthenticatedAdminUsuariosRoute
  '/empresa/$id/editar': typeof AuthenticatedEmpresaIdEditarRoute
  '/empresa/$id/posts': typeof AuthenticatedEmpresaIdPostsRoute
  '/empresa/$id/promocoes': typeof AuthenticatedEmpresaIdPromocoesRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/buscar': typeof BuscarRoute
  '/divulgar': typeof DivulgarRoute
  '/empresas': typeof EmpresasRoute
  '/favoritos': typeof FavoritosRoute
  '/login': typeof LoginRoute
  '/planos': typeof PlanosRoute
  '/promocoes': typeof PromocoesRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/_authenticated/completar-cadastro': typeof AuthenticatedCompletarCadastroRoute
  '/_authenticated/conta': typeof AuthenticatedContaRoute
  '/_authenticated/minha-empresa': typeof AuthenticatedMinhaEmpresaRoute
  '/_authenticated/reivindicar': typeof AuthenticatedReivindicarRoute
  '/categorias/$slug': typeof CategoriasSlugRoute
  '/checkout/retorno': typeof CheckoutRetornoRoute
  '/empresa/$slug': typeof EmpresaSlugRoute
  '/politicas/$slug': typeof PoliticasSlugRoute
  '/categorias/': typeof CategoriasIndexRoute
  '/politicas/': typeof PoliticasIndexRoute
  '/_authenticated/admin/banners': typeof AuthenticatedAdminBannersRoute
  '/_authenticated/admin/categorias': typeof AuthenticatedAdminCategoriasRoute
  '/_authenticated/admin/empresas': typeof AuthenticatedAdminEmpresasRoute
  '/_authenticated/admin/instituicoes': typeof AuthenticatedAdminInstituicoesRoute
  '/_authenticated/admin/migracoes': typeof AuthenticatedAdminMigracoesRoute
  '/_authenticated/admin/planos': typeof AuthenticatedAdminPlanosRoute
  '/_authenticated/admin/politicas': typeof AuthenticatedAdminPoliticasRoute
  '/_authenticated/admin/promocoes': typeof AuthenticatedAdminPromocoesRoute
  '/_authenticated/admin/reivindicacoes': typeof AuthenticatedAdminReivindicacoesRoute
  '/_authenticated/admin/usuarios': typeof AuthenticatedAdminUsuariosRoute
  '/_authenticated/empresa/$id/editar': typeof AuthenticatedEmpresaIdEditarRoute
  '/_authenticated/empresa/$id/posts': typeof AuthenticatedEmpresaIdPostsRoute
  '/_authenticated/empresa/$id/promocoes': typeof AuthenticatedEmpresaIdPromocoesRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/buscar'
    | '/divulgar'
    | '/empresas'
    | '/favoritos'
    | '/login'
    | '/planos'
    | '/promocoes'
    | '/reset-password'
    | '/admin'
    | '/completar-cadastro'
    | '/conta'
    | '/minha-empresa'
    | '/reivindicar'
    | '/categorias/$slug'
    | '/checkout/retorno'
    | '/empresa/$slug'
    | '/politicas/$slug'
    | '/categorias/'
    | '/politicas/'
    | '/admin/banners'
    | '/admin/categorias'
    | '/admin/empresas'
    | '/admin/instituicoes'
    | '/admin/migracoes'
    | '/admin/planos'
    | '/admin/politicas'
    | '/admin/promocoes'
    | '/admin/reivindicacoes'
    | '/admin/usuarios'
    | '/empresa/$id/editar'
    | '/empresa/$id/posts'
    | '/empresa/$id/promocoes'
    | '/api/public/payments/webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/buscar'
    | '/divulgar'
    | '/empresas'
    | '/favoritos'
    | '/login'
    | '/planos'
    | '/promocoes'
    | '/reset-password'
    | '/admin'
    | '/completar-cadastro'
    | '/conta'
    | '/minha-empresa'
    | '/reivindicar'
    | '/categorias/$slug'
    | '/checkout/retorno'
    | '/empresa/$slug'
    | '/politicas/$slug'
    | '/categorias'
    | '/politicas'
    | '/admin/banners'
    | '/admin/categorias'
    | '/admin/empresas'
    | '/admin/instituicoes'
    | '/admin/migracoes'
    | '/admin/planos'
    | '/admin/politicas'
    | '/admin/promocoes'
    | '/admin/reivindicacoes'
    | '/admin/usuarios'
    | '/empresa/$id/editar'
    | '/empresa/$id/posts'
    | '/empresa/$id/promocoes'
    | '/api/public/payments/webhook'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/buscar'
    | '/divulgar'
    | '/empresas'
    | '/favoritos'
    | '/login'
    | '/planos'
    | '/promocoes'
    | '/reset-password'
    | '/_authenticated/admin'
    | '/_authenticated/completar-cadastro'
    | '/_authenticated/conta'
    | '/_authenticated/minha-empresa'
    | '/_authenticated/reivindicar'
    | '/categorias/$slug'
    | '/checkout/retorno'
    | '/empresa/$slug'
    | '/politicas/$slug'
    | '/categorias/'
    | '/politicas/'
    | '/_authenticated/admin/banners'
    | '/_authenticated/admin/categorias'
    | '/_authenticated/admin/empresas'
    | '/_authenticated/admin/instituicoes'
    | '/_authenticated/admin/migracoes'
    | '/_authenticated/admin/planos'
    | '/_authenticated/admin/politicas'
    | '/_authenticated/admin/promocoes'
    | '/_authenticated/admin/reivindicacoes'
    | '/_authenticated/admin/usuarios'
    | '/_authenticated/empresa/$id/editar'
    | '/_authenticated/empresa/$id/posts'
    | '/_authenticated/empresa/$id/promocoes'
    | '/api/public/payments/webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  BuscarRoute: typeof BuscarRoute
  DivulgarRoute: typeof DivulgarRoute
  EmpresasRoute: typeof EmpresasRoute
  FavoritosRoute: typeof FavoritosRoute
  LoginRoute: typeof LoginRoute
  PlanosRoute: typeof PlanosRoute
  PromocoesRoute: typeof PromocoesRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  CategoriasSlugRoute: typeof CategoriasSlugRoute
  CheckoutRetornoRoute: typeof CheckoutRetornoRoute
  EmpresaSlugRoute: typeof EmpresaSlugRoute
  PoliticasSlugRoute: typeof PoliticasSlugRoute
  CategoriasIndexRoute: typeof CategoriasIndexRoute
  PoliticasIndexRoute: typeof PoliticasIndexRoute
  ApiPublicPaymentsWebhookRoute: typeof ApiPublicPaymentsWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/promocoes': {
      id: '/promocoes'
      path: '/promocoes'
      fullPath: '/promocoes'
      preLoaderRoute: typeof PromocoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/planos': {
      id: '/planos'
      path: '/planos'
      fullPath: '/planos'
      preLoaderRoute: typeof PlanosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/favoritos': {
      id: '/favoritos'
      path: '/favoritos'
      fullPath: '/favoritos'
      preLoaderRoute: typeof FavoritosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/empresas': {
      id: '/empresas'
      path: '/empresas'
      fullPath: '/empresas'
      preLoaderRoute: typeof EmpresasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/divulgar': {
      id: '/divulgar'
      path: '/divulgar'
      fullPath: '/divulgar'
      preLoaderRoute: typeof DivulgarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/buscar': {
      id: '/buscar'
      path: '/buscar'
      fullPath: '/buscar'
      preLoaderRoute: typeof BuscarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/politicas/': {
      id: '/politicas/'
      path: '/politicas'
      fullPath: '/politicas/'
      preLoaderRoute: typeof PoliticasIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categorias/': {
      id: '/categorias/'
      path: '/categorias'
      fullPath: '/categorias/'
      preLoaderRoute: typeof CategoriasIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/politicas/$slug': {
      id: '/politicas/$slug'
      path: '/politicas/$slug'
      fullPath: '/politicas/$slug'
      preLoaderRoute: typeof PoliticasSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/empresa/$slug': {
      id: '/empresa/$slug'
      path: '/empresa/$slug'
      fullPath: '/empresa/$slug'
      preLoaderRoute: typeof EmpresaSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout/retorno': {
      id: '/checkout/retorno'
      path: '/checkout/retorno'
      fullPath: '/checkout/retorno'
      preLoaderRoute: typeof CheckoutRetornoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categorias/$slug': {
      id: '/categorias/$slug'
      path: '/categorias/$slug'
      fullPath: '/categorias/$slug'
      preLoaderRoute: typeof CategoriasSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/reivindicar': {
      id: '/_authenticated/reivindicar'
      path: '/reivindicar'
      fullPath: '/reivindicar'
      preLoaderRoute: typeof AuthenticatedReivindicarRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/minha-empresa': {
      id: '/_authenticated/minha-empresa'
      path: '/minha-empresa'
      fullPath: '/minha-empresa'
      preLoaderRoute: typeof AuthenticatedMinhaEmpresaRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/conta': {
      id: '/_authenticated/conta'
      path: '/conta'
      fullPath: '/conta'
      preLoaderRoute: typeof AuthenticatedContaRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/completar-cadastro': {
      id: '/_authenticated/completar-cadastro'
      path: '/completar-cadastro'
      fullPath: '/completar-cadastro'
      preLoaderRoute: typeof AuthenticatedCompletarCadastroRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/usuarios': {
      id: '/_authenticated/admin/usuarios'
      path: '/usuarios'
      fullPath: '/admin/usuarios'
      preLoaderRoute: typeof AuthenticatedAdminUsuariosRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/reivindicacoes': {
      id: '/_authenticated/admin/reivindicacoes'
      path: '/reivindicacoes'
      fullPath: '/admin/reivindicacoes'
      preLoaderRoute: typeof AuthenticatedAdminReivindicacoesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/promocoes': {
      id: '/_authenticated/admin/promocoes'
      path: '/promocoes'
      fullPath: '/admin/promocoes'
      preLoaderRoute: typeof AuthenticatedAdminPromocoesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/politicas': {
      id: '/_authenticated/admin/politicas'
      path: '/politicas'
      fullPath: '/admin/politicas'
      preLoaderRoute: typeof AuthenticatedAdminPoliticasRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/planos': {
      id: '/_authenticated/admin/planos'
      path: '/planos'
      fullPath: '/admin/planos'
      preLoaderRoute: typeof AuthenticatedAdminPlanosRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/migracoes': {
      id: '/_authenticated/admin/migracoes'
      path: '/migracoes'
      fullPath: '/admin/migracoes'
      preLoaderRoute: typeof AuthenticatedAdminMigracoesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/instituicoes': {
      id: '/_authenticated/admin/instituicoes'
      path: '/instituicoes'
      fullPath: '/admin/instituicoes'
      preLoaderRoute: typeof AuthenticatedAdminInstituicoesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/empresas': {
      id: '/_authenticated/admin/empresas'
      path: '/empresas'
      fullPath: '/admin/empresas'
      preLoaderRoute: typeof AuthenticatedAdminEmpresasRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/categorias': {
      id: '/_authenticated/admin/categorias'
      path: '/categorias'
      fullPath: '/admin/categorias'
      preLoaderRoute: typeof AuthenticatedAdminCategoriasRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/banners': {
      id: '/_authenticated/admin/banners'
      path: '/banners'
      fullPath: '/admin/banners'
      preLoaderRoute: typeof AuthenticatedAdminBannersRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/api/public/payments/webhook': {
      id: '/api/public/payments/webhook'
      path: '/api/public/payments/webhook'
      fullPath: '/api/public/payments/webhook'
      preLoaderRoute: typeof ApiPublicPaymentsWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/empresa/$id/promocoes': {
      id: '/_authenticated/empresa/$id/promocoes'
      path: '/empresa/$id/promocoes'
      fullPath: '/empresa/$id/promocoes'
      preLoaderRoute: typeof AuthenticatedEmpresaIdPromocoesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/empresa/$id/posts': {
      id: '/_authenticated/empresa/$id/posts'
      path: '/empresa/$id/posts'
      fullPath: '/empresa/$id/posts'
      preLoaderRoute: typeof AuthenticatedEmpresaIdPostsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/empresa/$id/editar': {
      id: '/_authenticated/empresa/$id/editar'
      path: '/empresa/$id/editar'
      fullPath: '/empresa/$id/editar'
      preLoaderRoute: typeof AuthenticatedEmpresaIdEditarRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminBannersRoute: typeof AuthenticatedAdminBannersRoute
  AuthenticatedAdminCategoriasRoute: typeof AuthenticatedAdminCategoriasRoute
  AuthenticatedAdminEmpresasRoute: typeof AuthenticatedAdminEmpresasRoute
  AuthenticatedAdminInstituicoesRoute: typeof AuthenticatedAdminInstituicoesRoute
  AuthenticatedAdminMigracoesRoute: typeof AuthenticatedAdminMigracoesRoute
  AuthenticatedAdminPlanosRoute: typeof AuthenticatedAdminPlanosRoute
  AuthenticatedAdminPoliticasRoute: typeof AuthenticatedAdminPoliticasRoute
  AuthenticatedAdminPromocoesRoute: typeof AuthenticatedAdminPromocoesRoute
  AuthenticatedAdminReivindicacoesRoute: typeof AuthenticatedAdminReivindicacoesRoute
  AuthenticatedAdminUsuariosRoute: typeof AuthenticatedAdminUsuariosRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminBannersRoute: AuthenticatedAdminBannersRoute,
  AuthenticatedAdminCategoriasRoute: AuthenticatedAdminCategoriasRoute,
  AuthenticatedAdminEmpresasRoute: AuthenticatedAdminEmpresasRoute,
  AuthenticatedAdminInstituicoesRoute: AuthenticatedAdminInstituicoesRoute,
  AuthenticatedAdminMigracoesRoute: AuthenticatedAdminMigracoesRoute,
  AuthenticatedAdminPlanosRoute: AuthenticatedAdminPlanosRoute,
  AuthenticatedAdminPoliticasRoute: AuthenticatedAdminPoliticasRoute,
  AuthenticatedAdminPromocoesRoute: AuthenticatedAdminPromocoesRoute,
  AuthenticatedAdminReivindicacoesRoute: AuthenticatedAdminReivindicacoesRoute,
  AuthenticatedAdminUsuariosRoute: AuthenticatedAdminUsuariosRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
  AuthenticatedCompletarCadastroRoute: typeof AuthenticatedCompletarCadastroRoute
  AuthenticatedContaRoute: typeof AuthenticatedContaRoute
  AuthenticatedMinhaEmpresaRoute: typeof AuthenticatedMinhaEmpresaRoute
  AuthenticatedReivindicarRoute: typeof AuthenticatedReivindicarRoute
  AuthenticatedEmpresaIdEditarRoute: typeof AuthenticatedEmpresaIdEditarRoute
  AuthenticatedEmpresaIdPostsRoute: typeof AuthenticatedEmpresaIdPostsRoute
  AuthenticatedEmpresaIdPromocoesRoute: typeof AuthenticatedEmpresaIdPromocoesRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
  AuthenticatedCompletarCadastroRoute: AuthenticatedCompletarCadastroRoute,
  AuthenticatedContaRoute: AuthenticatedContaRoute,
  AuthenticatedMinhaEmpresaRoute: AuthenticatedMinhaEmpresaRoute,
  AuthenticatedReivindicarRoute: AuthenticatedReivindicarRoute,
  AuthenticatedEmpresaIdEditarRoute: AuthenticatedEmpresaIdEditarRoute,
  AuthenticatedEmpresaIdPostsRoute: AuthenticatedEmpresaIdPostsRoute,
  AuthenticatedEmpresaIdPromocoesRoute: AuthenticatedEmpresaIdPromocoesRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  BuscarRoute: BuscarRoute,
  DivulgarRoute: DivulgarRoute,
  EmpresasRoute: EmpresasRoute,
  FavoritosRoute: FavoritosRoute,
  LoginRoute: LoginRoute,
  PlanosRoute: PlanosRoute,
  PromocoesRoute: PromocoesRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  CategoriasSlugRoute: CategoriasSlugRoute,
  CheckoutRetornoRoute: CheckoutRetornoRoute,
  EmpresaSlugRoute: EmpresaSlugRoute,
  PoliticasSlugRoute: PoliticasSlugRoute,
  CategoriasIndexRoute: CategoriasIndexRoute,
  PoliticasIndexRoute: PoliticasIndexRoute,
  ApiPublicPaymentsWebhookRoute: ApiPublicPaymentsWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
